/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type MetaTag = {
  _type: "metaTag";
  metaAttributes?: Array<{
    _key: string;
  } & MetaAttribute>;
};

export type MetaAttribute = {
  _type: "metaAttribute";
  attributeKey?: string;
  attributeType?: "string" | "image";
  attributeValueImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  attributeValueString?: string;
};

export type SeoMetaFields = {
  _type: "seoMetaFields";
  nofollowAttributes?: boolean;
  metaTitle?: string;
  metaDescription?: string;
  seoKeywords?: Array<string>;
  openGraph?: OpenGraph;
  additionalMetaTags?: Array<{
    _key: string;
  } & MetaTag>;
  twitter?: Twitter;
};

export type Twitter = {
  _type: "twitter";
  cardType?: string;
  creator?: string;
  site?: string;
  handle?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type OpenGraph = {
  _type: "openGraph";
  url?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  title?: string;
  description?: string;
  siteName?: string;
};

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityFileAsset | Geopoint | Slug | MetaTag | MetaAttribute | SeoMetaFields | Twitter | SanityImageCrop | SanityImageHotspot | SanityImageAsset | SanityAssetSourceData | SanityImageMetadata | OpenGraph;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: seo
// Query: seo{    _type,  metaTitle,  nofollowAttributes,  seoKeywords,  metaDescription,  openGraph{    _type,  siteName,  url,  description,  title,  image{    _type,  crop{  _type,  right,  top,  left,  bottom  },  hotspot{  _type,  x,  y,  height,  width,  },  asset->{...}    }    },  twitter{    _type,  site,  creator,  cardType,  handle    },  additionalMetaTags[]{  _type,  metaAttributes[]{    _type,  attributeValueString,  attributeType,  attributeKey,  attributeValueImage{    _type,  crop{  _type,  right,  top,  left,  bottom  },  hotspot{  _type,  x,  y,  height,  width,  },  asset->{...}    }    }  }  }
export type SeoResult = never;
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] { _id, name, image, link, tags[]->{name},}
export type PROJECTS_QUERYResult = Array<never>;
// Variable: getHomePage
// Query: *[_type == "homePage"][0] {  hero {    title,    subtitle,    cta {      title,      url    },    secondaryCta {      title,      url    }  },  infrastructurePartners[]->,  networkStatsSection {    title,    subtitle,    stats[] {      title,      value    },    cta {       title,      url    }  },  innovatorFundSection {    title,    subtitle,    cta {      title,      url    },     secondaryCta {      title,        url    },    innovatorFundCard {      prefix,      postfix,      dollarAmount,      cta {        title,        url      }    }  },  sonicStackSection {    title,    subtitle,    features[] {      title,      icon,      bulletPoints    },    newsletterCta -> {      title,      subtitle,      signUpText    }  },}
export type GetHomePageResult = null;
// Variable: getTokenPage
// Query: *[_type == "tokenPage"][0] {  hero {    title,    subtitle,    cta {      title,      url    }  },  utilitySection {    title,    description,    utilityCards[] {      icon,      title,      description    }  },  migrationSection {    title,    description,    illustration,    cta {      title,      url    }  },  validatorNodeCard -> {    title,    description,    validatorIcons,    features[] {      title,      description    },    cta,    secondaryCta  },  newsletterCta->}
export type GetTokenPageResult = null;
// Variable: getBoomPage
// Query: *[_type == "boomPage"][0] {    hero {      image,      description    },    prizeCard {      fantomAmount    },    cards[] {      title,      description,      image,      cta {        title,        url      }    },    rankingCards,    bonusCards,    bountySection {        title,        description,        cta,        bounties[] {          title,          categories[] -> {            name          }      }    },    faq[] {        question,        answer        },    seo{    _type,  metaTitle,  nofollowAttributes,  seoKeywords,  metaDescription,  openGraph{    _type,  siteName,  url,  description,  title,  image{    _type,  crop{  _type,  right,  top,  left,  bottom  },  hotspot{  _type,  x,  y,  height,  width,  },  asset->{...}    }    },  twitter{    _type,  site,  creator,  cardType,  handle    },  additionalMetaTags[]{  _type,  metaAttributes[]{    _type,  attributeValueString,  attributeType,  attributeKey,  attributeValueImage{    _type,  crop{  _type,  right,  top,  left,  bottom  },  hotspot{  _type,  x,  y,  height,  width,  },  asset->{...}    }    }  }  }} 
export type GetBoomPageResult = null;
// Variable: getFooterData
// Query: *[_type == "footer"][0] {  logo,  copyrightNotice,  linkSections[] {    title,   links[] {      title,      url    }  }}
export type GetFooterDataResult = null;
